// <auto-generated />
namespace FantasyFootballCorner.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class player16 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(player16));
        
        string IMigrationMetadata.Id
        {
            get { return "201506012321147_player16"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
