// <auto-generated />
namespace FantasyFootballCorner.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class player2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(player2));
        
        string IMigrationMetadata.Id
        {
            get { return "201505071757332_player2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
